<%@ Page Title="Booking Information" Language="C#" MasterPageFile="~/Member.Master" AutoEventWireup="true" CodeBehind="BookingInformation.aspx.cs" Inherits="Planet_Fitness.SlotBooking.BookingInformation" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <h2 style="color: black;"><%: Title %></h2>
     <p class="text-danger">
        <asp:Literal runat="server" ID="ErrorMessage" />
     </p>
     <p style ="color:white;font-size:large;padding-left:40%">
        <asp:Literal runat="server" ID="SuccessMessage" />
     </p>
    <div style="padding-left: 22%;padding-top:5%;">
     <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="true" OnRowCreated ="GridView1_RowCreated" OnRowDeleting ="GridView1_RowDeleting"
          CssClass="CSSTableGenerator">
    </asp:GridView>
    </div>
</asp:Content>
